title = "Landmaster"  # From Git
organizationName = "nightcycle"
gitRepoUrl = "https://github.com/nightcycle/landmaster" # From Git
gitSourceBranch = "master"
projectName = "landmaster"
url = "https://nightcycle.github.io"
baseUrl = "/landmaster/"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "warn"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.png"
tagline = "A map generation framework."

[home]
enabled = true
includeReadme = true

[footer]
style = "dark"
copyright = "Copyright © 2022 Nightcycle Studios. Built with Moonwave and Docusaurus"


[[home.features]]
title = "Configurable"
description = "Empowers you to swap out your own noise maps for different outcomes."

[[home.features]]
title = "Parallel Enabled"
description = "Designed for usage alongside parallel-lua empowered workflows."

[[home.features]]
title = "Lightweight"
description = "A fancy way of saying this is a smaller project."