[package]
name = "nightcycle/landmaster"
description = "An in progress map generation framework."
version = "1.4.10"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
NoiseUtil = "nightcycle/noise-util@^1.0.5"
Draw = "nightcycle/draw@^1.0.6"
Signal = "nightcycle/signal@^1.0.2"
Maid = "nightcycle/maid@^1.0.4"
Vector = "nightcycle/vector@^1.0.2"
GeometryUtil = "nightcycle/geometry-util@^1.0.0"
CurveUtil = "nightcycle/curve-util@^1.0.0"